name: Test Workflow
on: 
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test:
    name: Simple Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Echo test
        run: echo "GitHub Actions is working!"
